In [1]:
# Q5
1*1/8+2*1/16+3*1/16

0.4375

In [4]:
# Q6
E=1*1/8+2*1/16+3*1/16
Var=(0-E)**2*3/4+(1-E)**2*1/8+(2-E)**2*1/16+(3-E)**2*1/16
Var

0.74609375

In [7]:
# Q7
Skew=(0-E)**3*3/4+(1-E)**3*1/8+(2-E)**3*1/16+(3-E)**3*1/16
Skew

1.24951171875

In [11]:
# Q8
# 2時間では4件　Fx=P(X<=4)
import math
Fx=1-math.exp(-4)
1-Fx

0.01831563888873422

In [12]:
# Q11
import numpy as np
A=np.array([[6,3,1],[3,4,3],[1,7,2]])*0.1
print(A)
B=A@A
print(B)

[[0.6 0.3 0.1]
 [0.3 0.4 0.3]
 [0.1 0.7 0.2]]
[[0.46 0.37 0.17]
 [0.33 0.46 0.21]
 [0.29 0.45 0.26]]


In [21]:
# Q12
import numpy as np
from scipy import stats

alpha = 0.95
x = np.array([9.0, 8.5, 9.3, 6.0, 10.5, 7.1])
y = np.array([5.0, 8.8, 3.8, 2.6, 5.7, 6.6])
n = len(x)
m = len(y)
X_ = np.mean(x)
Y_ = np.mean(y)
s1 = np.var(x, ddof=1)
s2 = np.var(y, ddof=1)

temp = s1 / m + s2 / n
nu = temp * temp / (s1 * s1 / (m * m * (m - 1)) + s2 * s2 / (n * n * (n - 1)))
t = stats.t.ppf(alpha + (1 - alpha) / 2, round(nu))
mean_sub = (X_ - Y_ - t * np.sqrt(temp), X_ - Y_ + t * np.sqrt(temp))
res = stats.ttest_ind(x, y)

print(X_, Y_)
print(s1, s2)
print(t)
print(mean_sub)
print(res)

8.4 5.416666666666667
2.608 4.729666666666668
2.2621571627409915
(0.48168569569679587, 5.484980970969871)
Ttest_indResult(statistic=2.6977295952118747, pvalue=0.02240049733296778)


In [22]:
# Q13
import numpy as np
from scipy import stats

alpha = 0.95
x = np.array([10.5, 5.5, 10.1, 7.2, 11.4, 8.6])
y = np.array([6.1, 7.5, 3.4, 2.8, 5.1, 6.9])
n = len(x)
m = len(y)
X_ = np.mean(x)
Y_ = np.mean(y)
s1 = np.var(x, ddof=1)
s2 = np.var(y, ddof=1)

temp = s1 / m + s2 / n
nu = temp * temp / (s1 * s1 / (m * m * (m - 1)) + s2 * s2 / (n * n * (n - 1)))
t = stats.t.ppf(alpha + (1 - alpha) / 2, round(nu))
mean_sub = (X_ - Y_ - t * np.sqrt(temp), X_ - Y_ + t * np.sqrt(temp))
res = stats.ttest_ind(x, y)

print(X_, Y_)
print(s1, s2)
print(t)
print(mean_sub)
print(res)

8.883333333333335 5.3
4.957666666666666 3.588
2.2281388519649385
(0.924203144107012, 6.242463522559658)
Ttest_indResult(statistic=3.0025473186267857, pvalue=0.013285701656250032)


In [23]:
# Q22
import numpy as np

height = np.array([40, 40, 56, 47, 115, 36, 72, 56])
weight = np.array([69, 32, 67, 40, 97, 55, 62, 49])

X=height.reshape(-1,1)
Y=weight.reshape(-1,1)

from sklearn import linear_model
clf = linear_model.LinearRegression()
clf.fit(X, Y)

# 回帰係数
print(clf.coef_)
 
# 切片 (誤差)
print(clf.intercept_)
 
# 決定係数
print(clf.score(X, Y))

[[0.59818298]]
[24.32993306]
0.5964612444913476


In [24]:
# Q23
import numpy as np

height = np.array([54, 26, 72, 55, 104, 31, 78, 55, 80])
weight = np.array([57, 29, 59, 54, 107, 52, 59, 71, 78])

X=height.reshape(-1,1)
Y=weight.reshape(-1,1)

from sklearn import linear_model
clf = linear_model.LinearRegression()
clf.fit(X, Y)

# 回帰係数
print(clf.coef_)
 
# 切片 (誤差)
print(clf.intercept_)
 
# 決定係数
print(clf.score(X, Y))

[[0.74736048]]
[16.80165913]
0.7438349827820743


In [27]:
# Q24
import numpy as np
from sklearn.decomposition import PCA
features = np.array([[1, -0.2], [-0.2, 1]])
pca = PCA()
pca.fit(features)
transformed = pca.fit_transform(features)
transformed

array([[ 8.48528137e-01,  5.55111512e-17],
       [-8.48528137e-01,  5.55111512e-17]])